site_name: Cookbook
site_url: http://recipes.paulsaary.de

theme:
  name: material
  #icon:
  #  repo: fontawesome/brands/github
  #  logo: fontawesome/solid/bowl-rice
  logo: icons/icon-128.png
  favicon: icons/favicon.ico
  custom_dir: overrides


  palette:
    #scheme: default
    scheme: otter


  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - md_in_html
  - attr_list
  - def_list

plugins:
  - search
  - privacy:
      cache: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
