---
name: ci
on:
  push:
    paths:
      - "cook/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build cook
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x

      - name: TEST
        env:
          FTP_USER: ${{ secrets.FTPUSER }}
          FTP_PASSWORD: ${{ secrets.FTPPASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          TESTSECRET: ${{ secrets.TESTSECRET }}
        run: |
          echo "Uploading to webspace"
          echo $TESTSECRET

      - name: Install dependencies
        run: |
          sudo apt install -y lftp
          python -m pip install 'pycook @ git+https://github.com/openpaul/pycook'
          pip install mkdocs mkdocs-material
      - name: Build Static Page
        run: |
          mkdocs build -c
      - name: Upload to Webspace
        env:
          FTP_USER: ${{ secrets.FTPUSER }}
          FTP_PASSWORD: ${{ secrets.FTPPASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          TESTSECRET: ${{ secrets.TESTSECRET }}
        run: |
          echo "Uploading to webspace"
          echo $TESTSECRET
          lftp --version
          lftp -e "mirror -R /home/runner/work/cookbook/cookbook/site/ .; quit" -p 22 -u $FTP_USER,$FTP_PASSWORD sftp://$SERVER
