---
name: ci
on:
  push:
    paths:
      - "cook/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build cook
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x

      - name: Install dependencies
        run: |
          sudo apt install -y expect
          python -m pip install 'pycook @ git+https://github.com/openpaul/pycook'
          pip install mkdocs mkdocs-material

      - name: Build Static Page
        run: |
          mkdocs build -c -v
          ls -lah site

      - name: Upload to Webspace
        env:
          FTP_USER: ${{ secrets.FTPUSER }}
          FTP_PASSWORD: ${{ secrets.FTPPASSWORD }}
          SERVER: ${{ secrets.SERVER }}
        run: |
          echo "Uploading to webspace"
          chmod +x  .github/sftp_upload.sh
          ./.github/sftp_upload.sh