---
name: ci
on:
  push:
    paths:
      - "cook/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build cook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x

      - name: Install dependencies
        run: |
          sudo apt install -y lftp
          python -m pip install 'pycook @ git+https://github.com/openpaul/pycook'
          pip install mkdocs mkdocs-material

      - name: Build and Upload to Webspace
        env:
          FTP_USER: ${{ secrets.FTPUSER }}
          FTP_PASSWORD: ${{ secrets.FTPPASSWORD }}
          SERVER: ${{ secrets.SERVER }}
        run: |
          mkdocs build -c
          chmod +x  .github/lftp.sh
          lftp --version
          bash .github/lftp.sh site ${FTP_USER} ${FTP_PASSWORD} ${SERVER} /